shared_buffers = 3GB
effective_cache_size = 8GB
work_mem = 16MB
maintenance_work_mem = 1GB
max_connections = 100
wal_buffers = 16MB
wal_compression = on
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9
max_wal_size = 1GB
min_wal_size = 256MB
autovacuum = on
autovacuum_max_workers = 3
autovacuum_naptime = 30s
autovacuum_vacuum_scale_factor = 0.1
autovacuum_analyze_scale_factor = 0.05
autovacuum_vacuum_cost_limit = 2000
